#!/bin/bash

vmware-hgfsclient | while read folder; do
  echo "[i] Mounting ${folder}   (/root/Desktop/${folder})"
  mkdir -p "/root/Desktop/${folder}"
  umount -f "/root/Desktop/${folder}" 2>/dev/null
  vmhgfs-fuse -o allow_other -o auto_unmount ".host:/${folder}" "/root/Desktop/${folder}"
done

sleep 2s
